# -*- coding: utf-8 -*-
"""Yash_PG_Lab_assignment_4b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172YzBMcvGVbRFoXYdBfp15fjuj2rJV39

###Importing the required libraries
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, AveragePooling2D, Flatten, Dense, Dropout, Activation
import matplotlib.pyplot as plt

"""###Load he dataset and add padding"""

# Load mnist dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = np.pad(x_train, ((0, 0), (2, 2), (2, 2)), mode='constant')
x_test = np.pad(x_test, ((0, 0), (2, 2), (2, 2)), mode='constant')

print(x_train.shape)
print(x_test.shape)

"""###Define the model architecture and train the model"""

model = Sequential()

# Layer 1
model.add(Conv2D(6, (5, 5), strides=1, padding='valid', input_shape=(32, 32, 1)))
model.add(Activation('tanh'))
model.add(AveragePooling2D(pool_size=(2, 2), strides=2))

# Layer 2
model.add(Conv2D(16, (5, 5), strides=1, padding='valid'))
model.add(Activation('tanh'))
model.add(AveragePooling2D(pool_size=(2, 2), strides=2))

# Flatten and fully connected layers
model.add(Flatten())
model.add(Dense(120))
model.add(Activation('tanh'))
model.add(Dense(84))
model.add(Activation('tanh'))

# Output layer
model.add(Dense(10))
model.add(Activation('softmax'))


model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

#Scaling the data so that it ranges between 0 to 1
x_train = np.expand_dims(x_train, -1).astype('float32') / 255
x_test = np.expand_dims(x_test, -1).astype('float32') / 255

# Train the model
history = model.fit(x_train, y_train, epochs=5, batch_size=64, validation_data=(x_test, y_test))

# Save the model
model.save('lenet5_mnist.keras')
